### ISSUE TITLE
Fullscreen player not working

### ISSUE THREAD

**Issue by TobiasAndersen83** [amittkSharma/react-video-player-extended#30]
Hi, i was browsing your code, and i tried out the example page [Example page](https://amittksharma.github.io/react-video-player-extended/example/index.html), but there seems to be an error with closing the full screen. 

When trying to close full screen by using Escape, it is just changing into a smaller different dimension, but does not fully close the video player, and you have to use either the symbol in the bottom right corner or the X in the top right, to actually exit the full screen. 

Curious if i am the only one with this issue, and/or if there was a solution available!

**Comment by rr4ev** [comment]
Same issue here. It seems that when you click escape you run the built-in browser exit full screen functionality, but the one from this package, responsible for reverting the state of the video player (which happens when you click the 'x' button when in fullscreen), doesn't work.

**Comment by amittkSharma** [comment]
The issue is resolved and merged into the main branch. It will be released soon
