### ISSUE TITLE
Add support for continuous marker

### ISSUE THREAD

**Issue by tran302** [amittkSharma/react-video-player-extended#31]
In addition to marker on a specific frame, continuous marker would be beneficial to highlight specific time intervals in a video.

**Comment by amittkSharma** [comment]
Continuous marker functionality is implemented in version 9.1.0, but it is not time interval-based. 

One will get the markers continuously as the video progresses but this functionality will not add or highlight any marker on the video progress bar. 

Could you please elaborate on the use case for the interval-based markers? Here markers are for annotating the frames in the video.

**Comment by tran302** [comment]
@amittkSharma I'm working on an application that detects periods (continuous frames like 5 second mark ~ 15 second mark) of the given uploaded video where humans appear in the video. Using html5 video player, it currently plays only those detected periods, but it'd be more useful if the video progress bar highlights those detected periods to get a better picture quickly on where in the video humans appear, how long they appear out of the entire video duration (as it could be hours in duration in our use case), etc.
