### ISSUE TITLE
Npm package version update? 

### ISSUE THREAD

**Issue by vikiminki** [amittkSharma/react-video-player-extended#48]
Hi! Is there a reason the latest tag (9.2.1) is not available on npm? The functionality I want to use works fine when I try to just add it in your example (using the current version 9.2.1 of this package), but it doesn't work for 9.1.0. I don't yet know if that is the issue but it seems possible as it works well in the example-project.. just figured I'd drop a question about it here to check

**Comment by amittkSharma** [comment]
The newer version will be released next week.
