### ISSUE TITLE
Set a marker by a custom value

### ISSUE THREAD

**Issue by gborasio** [amittkSharma/react-video-player-extended#53]
Hi all i see that the AddMarker insert a Marker with the function handleMarkerAdd that take information by (marker) with a current time . 
i want to insert in an input box a time start and time end , and pressing a button i want to insert a marker for the start and a marker for the end.
is it a way to do this?

**Comment by amittkSharma** [comment]
Hi, The add marker feature is to annotate the video at a specific time. 

Please correct me if I misunderstood the requirement, what you want is to mark the whole section of the video with the start and end times.  

This kind of feature is not yet supported but feature will be released.

Regards

**Comment by borasio** [comment]
Yes could be useful to indicate a start time and end time and call Addmarker function not to insert marker at current point but at a different point (input value)
